services:
  - type: web
    name: stock-trading-system
    env: node
    buildCommand: npm install && npm install --prefix backend && npm install --prefix frontend && cd frontend && npm run build:css
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: KIS_APP_KEY
        sync: false
      - key: KIS_APP_SECRET
        sync: false
      - key: KIS_ACCOUNT_NUMBER
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
